import React, { useState } from "react";
import Head from "next/head";
import { Carousel } from "@material-tailwind/react";
import { CarouselProps } from "@material-tailwind/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>EngineStud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    

      <div class="flex justify-center mx-2 md:hidden">
        <div class="w-full md:w-4/5 aspect-w-1920 aspect-h-780">
          <div class="overflow-hidden relative">
            <div className="flex transition-transform ease-out duration-500" style={{ transform: 'translateX(-500%)' }}>
              <img class="w-full h-full object-cover" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/squarebanner/6.webp" alt="Slide 1" />
              <img class="w-full h-full object-cover" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/squarebanner/2.webp" alt="Slide 2" />
              <img class="w-full h-full object-cover" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/squarebanner/3.webp" alt="Slide 3" />
              <img class="w-full h-full object-cover" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/squarebanner/4.webp" alt="Slide 4" />
              <img class="w-full h-full object-cover" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/squarebanner/5.webp" alt="Slide 5" />
              <img class="w-full h-full object-cover" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/squarebanner/1.webp" alt="Slide 6" />
            </div>
            <div class="absolute inset-0 flex items-center justify-between p-4">
              <button class="p-0 md:rounded-full md:shadow md:bg-white text-white md:text-gray-800">
                <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 24 24" height="36" width="36" xmlns="http://www.w3.org/2000/svg">
                  <path fill="none" d="M0 0h24v24H0z">

                  </path><path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path></svg></button>
              <button class="p-0 md:rounded-full md:shadow md:bg-white text-white md:text-gray-800"><svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 24 24" height="36" width="36" xmlns="http://www.w3.org/2000/svg"><path fill="none" d="M0 0h24v24H0z"></path><path d="M10 6L8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6z"></path></svg>
              </button>
            </div>
            <div class="absolute bottom-4 right-0 left-0">
              <div class="flex items-center justify-center mb-4 aos-init aos-animate" data-aos="zoom-in-up"><a href="/tshirts" previewlistener="true">
                <button class="bg-white hover:bg-gray-200 text-black font-bold py-2 px-6 md:py-2 md:px-8 rounded-xl text-base md:text-lg xl:text-2xl shadow-lg">Shop Now</button></a></div><div class="flex items-center justify-center gap-2"><div class="transition-all w-2 h-2 md:w-3 md:h-3 bg-white rounded-full bg-opacity-50"></div><div class="transition-all w-2 h-2 md:w-3 md:h-3 bg-white rounded-full bg-opacity-50"></div><div class="transition-all w-2 h-2 md:w-3 md:h-3 bg-white rounded-full bg-opacity-50"></div><div class="transition-all w-2 h-2 md:w-3 md:h-3 bg-white rounded-full bg-opacity-50"></div><div class="transition-all w-2 h-2 md:w-3 md:h-3 bg-white rounded-full bg-opacity-50"></div><div class="transition-all w-2 h-2 md:w-3 md:h-3 bg-white rounded-full p-1"></div></div></div></div></div></div>

      <div className="flex flex-wrap -m-4 justify-center">
        <div class="md:w-1/3 sm:w-1/2 p-2 w-[50%]">
          <div class="p-2 rounded-lg overflow-hidden cursor-pointer aos-init aos-animate" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom">
            <a href="/theme/anime-tshirts" previewlistener="true">
              <img class="rounded w-full object-cover object-center mb-2 transition-transform duration-300 hover:scale-110" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/themes/anime.webp" alt="content" />
            </a>
          </div>
        </div>
        <div class="md:w-1/3 sm:w-1/2 p-2 w-[50%]">

          <div class="p-2 rounded-lg overflow-hidden cursor-pointer aos-init aos-animate" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom">
            <a href="/theme/combo-tshirts" previewlistener="true">
              <img class="rounded w-full object-cover object-center mb-2 transition-transform duration-300 hover:scale-110" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/themes/combooffers.webp" alt="content" />
            </a>
          </div>
        </div>
        <div class="md:w-1/3 sm:w-1/2 p-2 w-[50%]">
          <div class="p-2 rounded-lg overflow-hidden cursor-pointer aos-init aos-animate" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom">
            <a href="/theme/customized-tshirts" previewlistener="true">
              <img class="rounded w-full object-cover object-center mb-2 transition-transform duration-300 hover:scale-110" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/themes/customized.webp" alt="content" />
            </a>
          </div>
        </div>
        <div class="md:w-1/3 sm:w-1/2 p-2 w-[50%] aos-init aos-animate" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom">
          <div class="p-2 rounded-lg overflow-hidden cursor-pointer">
            <a href="/theme/gym-tshirts" previewlistener="true">
              <img class="rounded w-full object-cover object-center mb-2 transition-transform duration-300 hover:scale-110" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/themes/fitness.webp" alt="content" />
            </a>
          </div>
        </div>
        <div class="md:w-1/3 sm:w-1/2 p-2 w-[50%] aos-init aos-animate" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom">
          <div class="p-2 rounded-lg overflow-hidden cursor-pointer">
            <a href="/theme/gaming-tshirts" previewlistener="true"><img class="rounded w-full object-cover object-center mb-2 transition-transform duration-300 hover:scale-110" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/themes/gaming.webp" alt="content" /></a></div></div><div class="md:w-1/3 sm:w-1/2 p-2 w-[50%] aos-init aos-animate" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom"><div class="p-2 rounded-lg overflow-hidden cursor-pointer"><a href="/theme/lifestyle-tshirts" previewlistener="true"><img class="rounded w-full object-cover object-center mb-2 transition-transform duration-300 hover:scale-110" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/themes/lifestyle.webp" alt="content" /></a></div></div><div class="md:w-1/3 sm:w-1/2 p-2 w-[50%] aos-init" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom"><div class="p-2 rounded-lg overflow-hidden cursor-pointer"><a href="/theme/coding-tshirts" previewlistener="true"><img class="rounded w-full object-cover object-center mb-2 transition-transform duration-300 hover:scale-110" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/themes/programming.webp" alt="content" /></a></div></div><div class="md:w-1/3 sm:w-1/2 p-2 w-[50%] aos-init" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom"><div class="p-2 rounded-lg overflow-hidden cursor-pointer"><a href="/theme/trending-tshirts" previewlistener="true"><img class="rounded w-full object-cover object-center mb-2 transition-transform duration-300 hover:scale-110" src="https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/themes/trending.webp" alt="content" /></a></div></div></div>
    </>
  );
}
